version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel_api_jwt' 
      MYSQL_USER: 'root'         
      MYSQL_PASSWORD: 'password' 
      MYSQL_ROOT_PASSWORD: 'password' 
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local